### ISSUE TITLE
Crash with struct definition in functions

### ISSUE THREAD

**Issue by adam-sse** [KernelHaven/srcMLExtractor#2]
The following code inside a function leads to a crash:
```C
struct {
    int a;
} str;
```

E.g. in a function like this:
```C
int structDecl() {
	struct {
		int a;
	} str;
	str.a = 1;
	
	return str.a;
}
```

Stacktrace:
```
java.lang.RuntimeException: makeCode() Expected CodeUnitCodeUnit or PreprocessorBlock, got TranslationUnit
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.makeCode(TranslationUnitToAstConverter.java:384)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.createTypeDef(TranslationUnitToAstConverter.java:311)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.convertTranslationUnit(TranslationUnitToAstConverter.java:188)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.convert(TranslationUnitToAstConverter.java:79)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.convertTranslationUnit(TranslationUnitToAstConverter.java:236)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.convert(TranslationUnitToAstConverter.java:79)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.convertTranslationUnit(TranslationUnitToAstConverter.java:221)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.convert(TranslationUnitToAstConverter.java:79)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.convertTranslationUnit(TranslationUnitToAstConverter.java:209)
	at net.ssehub.kernel_haven.srcml.transformation.testing.TranslationUnitToAstConverter.convert(TranslationUnitToAstConverter.java:79)
	at net.ssehub.kernel_haven.srcml.transformation.testing.XmlToSyntaxElementConverter.getAst(XmlToSyntaxElementConverter.java:145)
	at net.ssehub.kernel_haven.srcml.xml.AbstractAstConverter.getResult(AbstractAstConverter.java:43)
	at net.ssehub.kernel_haven.srcml.xml.XmlToAstConverter.parseToAst(XmlToAstConverter.java:56)
	at net.ssehub.kernel_haven.srcml.SrcMLExtractor.runOnFile(SrcMLExtractor.java:116)
```

**Comment by adam-sse** [comment]
Fixed by dedd6797b763bf7c4f4a80f6d55ba377f9eada43.
